# WEBSCRAPING ENVIRONMENT SETUP 

# conda env create -f 00_environment_setup/conda_environment.yml
# conda env update --file 00_environment_setup/conda_environment.yml --prune
# conda env remove --name webscraping_env


name: webscraping_python_env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
    - pandas==1.5.3
    - numpy==1.24.1
    - beautifulsoup4==4.11.1
    - lxml==4.9.2
    - re101==0.4.0
    - requests==2.28.2
    - openpyxl==3.0.10
    - XlsxWriter==3.0.7
    - ipykernel==6.20.2
